---
- name: Install git
  yum: name=git state=latest
  tags:
    - jenkins
    - plugin

- name: Get jenkins cli
  get_url: url="http://{{ localhost }}:8080/{{ jenkins_cli_dir }}" dest=~/
  tags:
    - jenkins
    - plugin

- name: Install git plugin
  command: java  -jar jenkins-cli.jar -s http://{{ localhost }}:8080 install-plugin git
  tags:
    - jenkins
    - plugin

- name: Restart jenkins
  command: curl http://{{ localhost }}:8080/safeRestart/
  tags:
    - jenkins
    - plugin