---
- name: Wait for port {{ jenkins_port }} availability
  wait_for: port={{ jenkins_port }} timeout=60
  tags:
    - jenkins
    - plugin

- name: Install git
  yum: name=git state=latest
  tags:
    - jenkins
    - plugin

- name: Get jenkins cli
  get_url: url="http://{{ jenkins_host_name }}:{{ jenkins_port }}/{{ jenkins_cli_path }}" dest=~/
  tags:
    - jenkins
    - plugin

- name: Wait for updates/default.json to exist
  wait_for: path=/var/lib/jenkins/updates/default.json timeout=180
  tags:
    - jenkins
    - plugin

- name: Install git plugin
  command: java  -jar jenkins-cli.jar -s http://{{ jenkins_host_name }}:{{ jenkins_port }} install-plugin git
  tags:
    - jenkins
    - plugin

- name: Restart jenkins
  command: curl http://{{ jenkins_host_name }}:{{ jenkins_port }}/safeRestart/
  tags:
    - jenkins
    - plugin